### ISSUE TITLE
Create automated user that can be used with openedx and edx

### ISSUE THREAD

**Issue by mumer92** [openedx/tcril-engineering#224]
### Firm Name

2U

### Urgency

Medium

### Requested Change

We are in process of automating iOS build system and one requirement of building edX iOS app is to utilize a config repo which contains keys and urls that are pointing to server.
In order to utlize that config repo in github actions to make a build, we need a bot account token which will have access to config repo.

We need an automated user from the TCRIL team whose token is added as a secret in Github action and available for repo https://github.com/openedx/edx-app-ios)

SRE can add and give this user permission to clone repo. edx/edx-mobile-config

https://github.com/edx/edx-mobile-config
https://github.com/openedx/edx-app-ios

### Reasoning

In order to clone edx-mobile-config into edx-ios, we need a user that can access to both repos so it can handle this process inside Github Actions.

**Comment by mumer92** [comment]
@sarina 
for full context, please check this jira [issue](https://openedx.atlassian.net/browse/DOS-3044)
as Nadeem explained there, we can setup a user (or bot) specifically for github actions that have access to both sides, i.e edx-internal and open-edx (edx-mobile-config and edx-ios) that way, we could be able to clone internal repo inside github actions in which build process will take place.

**Comment by sarina** [comment]
@mumer92 ah. This feels like a reasonably sized piece of engineering work, and I don't know where to start. I think, since it's your need, your team should develop the bot and we can help figure out how to get the permissions part sorted out.

I also cannot see that issue.

**Comment by mumer92** [comment]
@sarina what should be the starting point? Would it help to have a user created just for this purpose, that can have access to both repos and use it inside github actions? I have already added a request to 2U helpdesk for a email that we also need inside apple developer program which we will be using for managing builds (build, sign and upload to testflight).

**Comment by sarina** [comment]
Hi @mumer92 - we've done some internal discussion. We believe this is what you're trying to do:

* Automate openedx/edx-app-ios and openedx/edx-app-android builds. Builds for the edX-branded mobile app involve pulling in a private edx/edx-mobile-config repo.
* Build the edX app to run via a GHA workflow to run in the mobile app repos. 
* To build your desired GHA workflows, you would need to have a personal access token granting both (a) write access to the mobile app repos and (b) read access to the private edX mobile config repos.
* So, you want us to create a GitHub "bot" account, give it write access to the mobile app repos, then tell SRE the username so that SRE would give it read access to the edX mobile config repos. 
* Then, we would generate a personal access token from the bot account and expose in the mobile app repos GHA workflows as a token that can be used to build the edX apps.

There are a few problems and GitHub Terms of Service violations with this approach:
1. GitHub is strongly against bot accounts. New bot accounts should not be made; GitHub Apps should be used.
2. 2U is a for-profit company and as such cannot be building from Actions in the openedx non-profit account. We get free unlimited GitHub actions in this account for *non-profit* use. Building the 2U/edX mobile app would be using the Actions for *commercial* use.

As such, your team will need to figure out a way of building that doesn't use our Actions minutes. We cannot support edx-internal builds in the openedx organization.

**Comment by mumer92** [comment]
@sarina what are your thoughts? what should be a feasible way to move forward with this?

**Comment by sarina** [comment]
@mumer92 since this is your project, and you're working off a Jira ticket I cannot see, I suggest you go back with your team and brainstorm some ideas. If you have some thoughts you'd like to bounce off of us, we can give advice. We are an engineering team with our own priorities; these tickets are meant to mostly be permissions requests, not a place for project requests.

If this project is not one you can do, we can prioritize it in our backlog.

**Comment by mumer92** [comment]
Sure, Thankyou for that.
