### ISSUE TITLE
[GH Request] Issue for action runners for openedx org?

### ISSUE THREAD

**Issue by dianekaplan** [openedx/tcril-engineering#270]
### Firm Name

2U OCM (aka edX)

### Urgency

Moderate: Monday okay if busy

### Problem/Request

hello, tcril! 

I have an [build](https://github.com/openedx/ecommerce/pull/3721) in the ecommerce repo where three of the github actions have been 'Waiting for a runner to pick up this job...' for more than an hour. Usually they're fairly prompt- could you check if there's just a lot of jobs/usage on the openedx org Github hosted runners page, whether there's something wrong, etc? 

(Adam Blackwell only had permissions to check on the edX org, but suggested that Kyle could take a look for openedx). 

Update: we cancelled and reran it, second try waiting 20 minutes so far

thanks in advance for any info you can provide!
Diane

### Reasoning

n/a- info requested, not a change

**Comment by ormsbee** [comment]
It looks like the [CI checks](https://github.com/openedx/ecommerce/actions/workflows/ci.yml) haven't run successfully since last month? Our GitHub-hosted runners page shows that there are no running jobs, so it's not backed up on requests. It is entirely possible that this is configured incorrectly though–I'm not really familiar with how GitHub Actions works.

If it's not critical to get before the weekend, I'm going to punt this over to @feanil when he gets back from PTO on Monday.

**Comment by dianekaplan** [comment]
Thanks @ormsbee for confirming that there aren't any running jobs!

Yes we've had a failure in the quality-and-jobs failure that I'm investigating, and the difference with that recent build was that instead of running and hitting that error, the actions were indefinitely 'waiting for a runner' and not even starting. 

Strangely, I get these to run again when I'd made a different change, repushed, made my change again, repushed, so I'm no longer stuck! Thanks for having a look!

**Comment by feanil** [comment]
Sounds like the immediate issue is resolved but the underlying issue of the ecommerce tests failing on master is still there, I've let Ben and Colin know via Slack about it.
