### ISSUE TITLE
[GH Request] Unreachable docs in the Maple Release

### ISSUE THREAD

**Issue by TanahaRG** [openedx/tcril-engineering#302]
### Firm Name

RG

### Urgency

Low

### Problem/Request

IIn the Maple Release Notes the link lead to the restricted page. The page should be open.

There is a link to the readthedocs https://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/maple.html#course-authoring-import-messaging-validation

There is a restricted page https://openedx.atlassian.net/wiki/spaces/PT/pages/2594275334/Course+Import+Work

There is a text: Now educators will see specific error messages in the course import area of Studio. A full list of messages shown to educators is [documented in Confluence](https://openedx.atlassian.net/wiki/spaces/PT/pages/2594275334/Course+Import+Work). For developers, these errors are logged and can exported to a New Relic, Splunk, etc.

### Reasoning

Because there is a public page that has a private link. 
I want our clients or our support to have the place where they can read about errors and what they mean

**Comment by feanil** [comment]
@arbrandes I think there is enough 2U specific stuff on that page that we shouldn't just change the premissions on the page but pull out the relevant content to a more public place.  You should be able to view and edit the page and pull out the relevant content.  If you think we should open up the whole page, we should figure out what the process is for consulting with 2U before we do that because that's a pre-requisite of opening up whole pages.
