### ISSUE TITLE
How is the OSCM user configured in openedx.atlassian.net?

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#312]
What permissions, etc are on this user? https://openedx.atlassian.net/jira/people/search?q=OSCM

We need to be sure the parallel user is correct in 2u-internal.atlassian.net.

**Comment by feanil** [comment]
@nedbat I took a look and it's not super easy to see.  This user is in the following groups: 

* confluence-users
* contributors
* jira-users
* _licensed-jira

If you tell me which spaces you want to know more about, I can look up the permissions for those groups in the relevant spaces.  Otherwise, this is all I have for now.

**Comment by nedbat** [comment]
Thanks, that will do for now.  I'll come back if I need more.
