### ISSUE TITLE
[GH Request] Grant triage role on public-engineering to arbi-bom team

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#322]
### Firm Name

2U

### Urgency

Medium Urgency - needed to streamline maintenance issue creation

### Requested Change

Please grant the arbi-bom team the triage role on the public-engineering repository.

### Reasoning

In the discussion on how to create tickets for edx-platform maintenance tasks (so that anybody in the Open edX community could implement them), we decided to create them as GitHub Issues in the public-engineering repository with the "maintenance" and "help wanted" labels.  But the Arbi-BOM team, which plans to create a few dozen such issues, currently lacks permission to assign labels in that repo.  This would be much easier if they were granted the "triage" role on that rep, the minimum permission sufficient to assign labels.  Otherwise they'll either need to ask me to come back much after the tickets have been created to assign the labels on all these tickets (which doesn't feel like a good use of my time), or open tCRIL issues to request that the labels be applied to batches of new issues.

**Comment by Carlos-Muniz** [comment]
Thanks for the request. I will get to this ticket on Monday.

**Comment by Carlos-Muniz** [comment]
Just an update, still working on this.

**Comment by Carlos-Muniz** [comment]
Thank you for your request. Instead of granting the "triage" role to the `Arbi-BOM` team, the public-engineering repo has inherited a GitHub workflow originally from the build-test-release-wg repo called `add-remove-label-on-comment` (renamed from `label-on-comment`). This should allow the team to assign and remove labels to issues, without your intercession. Instructions for how to use the workflow are in a comment in the workflow file. Please let me know if there are any issues or questions.

Summary of Relevant Actions taken:
- [.github PR #12](https://github.com/openedx/.github/pull/12) to copy the GH Workflow to the .github repo
- [public-engineering PR #87](https://github.com/openedx/public-engineering/pull/87) to inherit the GH Workflow from .github repo
