### ISSUE TITLE
Archive Old Solutions Repos 

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#58]
These repos were meant to be retired after the end of the work edX did with one of its partners.  Unfortunately they made it into the openedx org. 

Please note, that we don’t have clarity on legal ownership around them, so it would be nice to get rid of them sooner than later. They should be archived and moved to the `openedx-unsupported` org.

Here is the list:
-  https://github.com/openedx/xblock-ooyala
-  https://github.com/openedx/xblock-group-project
-  https://github.com/openedx/xblock-mentoring
-  https://github.com/openedx/xblock-discussion
-  https://github.com/openedx/xblock-drag-and-drop

**Comment by kdmccormick** [comment]
@feanil I'm not sure all of these should be archived. Looking at the [master list](https://docs.google.com/spreadsheets/d/1vxuwG9z7-iHXuIFUVrxR8Giq8kvDvMrLJE4FrrehJnc/edit#gid=0)...

These two repos existed in the `edx` org and also had forks in `edx-solutions`. I am guessing that @natabene had them flagged for archival because the forks were meant to be archived:
* xblock-utils (I personally can attest that this is still in use)
* django-splash (never heard of this one)

These existed in the `edx` org but **didn't** exist as `edx-solutions` forks at the time of transfer. Not sure why they're on this list; maybe only Yonkers used them? We should probably check out the legal repo list that Nell shared to be sure.

* edx-search (Courseware search. I think some folks in the community use this, although edX.org toggles it of for non-admins)
* edx-milestones (not sure about this one)

**Comment by natabene** [comment]
I am happy to jump on a call to clarify things if needed. Lots of background with that contract.

**Comment by natabene** [comment]
@kdmccormick I think you are right about edx-search and edx-milestones. Whatever openedx has, can stay. I got confused because if edx-solutions repos with this name were moved, they would have the same URL. I actually found both of them in edx-unsupported: https://github.com/edx-unsupported/edx-solutions-edx-milestones and https://github.com/edx-unsupported/edx-solutions-edx-search.

**Comment by kdmccormick** [comment]
No problem, thanks @natabene . I'm excited that we can archive those five repos!

**Comment by kdmccormick** [comment]
@ormsbee moved the repos to https://github.com/openedx-unsupported and archived them 👍🏻
