### ISSUE TITLE
[GH Request] Add viktorrusakov as a member to the `paragon-triage` Github team again

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/tcril-engineering#637]
### Firm Name

2U

### Urgency

High; engineer needs access to manage Paragon project board.

### Requested Change

Viktor Rusakov ([viktorrusakov](https://github.com/ViktorRusakov)) needs "Triage" access to the Paragon Working Group [project board](https://github.com/orgs/openedx/projects/43) again.

This was previously done through this newly created Github team: https://github.com/orgs/openedx/teams/paragon-triage/members

However, Viktor was recently removed from this Github team.

Thanks!

### Reasoning

Viktor (incorrectly) recently lost his access to manage the Paragon Working Group [project board](https://github.com/orgs/openedx/projects/43) again through https://github.com/openedx/tcril-engineering/issues/622.

**Comment by kdmccormick** [comment]
Taking a look.

**Comment by kdmccormick** [comment]
Alright, @viktorrusakov should see an invitation back into the org at https://github.com/openedx

@adamstankiewicz , as project admin, you should then be able to give him write access to https://github.com/orgs/openedx/projects/43/settings/access again.

Sorry for the inconvenience! Let me know if there are any issues.

**Comment by adamstankiewicz** [comment]
@kdmccormick Thanks for the update. I have a couple follow-up questions. 

Originally, the Raccoon Gang engineers (including Viktor) lost their access through [this issue](https://github.com/openedx/public-engineering/issues/169). The result from that issue was that Adolfo (IIRC) created a new [paragon-triage](https://github.com/orgs/openedx/teams/paragon-triage/members), as the mechanism by which to give the Raccoon Gang engineers (and others) "Triage" access to the repository. 

However, giving "Triage" access via [the link you provided](https://github.com/orgs/openedx/projects/43/settings/access) is a different approach than this previously suggestion to use a new `paragon-triage` Github team. I also don't have permissions to add users to that Github team (not sure if I'm supposed to).

Given there's now 2 conflicting approaches recommended to grant "Triage" access here, which would you recommend moving forward? The previously mentioned solution of `paragon-triage` Github team or by managing the project's access settings directly?

I'd like to be giving "Triage" access to the Raccoon Gang engineers in a consistent way. Thanks!

**Comment by adamstankiewicz** [comment]
Ha, right as I commented that, Viktor informed me has actually got access back to the `paragon-triage` Github team. It wasn't entirely clear this was going to be the case in the given solution. 

@kdmccormick You can pretty much disregard the above message :) Though, I guess I do still wonder about whether I should be able to access to add members to the `paragon-triage` Github team.

**Comment by kdmccormick** [comment]
Good questions @adamstankiewicz . There are two different classes of GitHub access which, which we should deconflate:

* Repository access (levels: read, triage, write, admin)
* Project access (levels: read, write, admin)

Giving someone triage-or-higher access to a repository (like [paragon](https://github.com/openedx/paragon)) gives them the ability to edit that repository's issues and associated issue-level metadata, like labels, assignees, and milestones. In particular, the `paragon-triage` team grants triage access to the paragon repository. I added Viktor the that team when I added him back to the org, which I should've been clearer about--my bad!

Giving someone write access to a project (like [Paragon Working Group](https://github.com/orgs/openedx/projects/43/views/15)) gives them the ability to manage project-level metadata, like status, boards, and any custom columns you create. I asked you to add Viktor to the PWG project because I thought you'd want to, but it's totally up to you as admin of that project. Unlike repository access, you don't need to go through us for that.

> Though, I guess I do still wonder about whether I should be able to access to add members to the paragon-triage Github team.

Yeahhhh, unfortunately, we are currently wary of granting others the ability to add folks to teams, since it circumvents our vetting all openedx org access changes. I agree, though, that something like triage access is pretty harmless. I'll raise it at our next team retro and maybe we can get this part of the process loosened up.

**Comment by adamstankiewicz** [comment]
Awesome, thank you for the helpful clarifications, Kyle! :) 

> Yeahhhh, unfortunately, we are currently wary of granting others the ability to add folks to teams, since it circumvents our vetting all openedx org access changes. I'll raise it at our next team retro and maybe we can get this part of the process loosened up.

Totally understandable. Appreciate it in advance! No worries if not; it's pretty straightforward to go through the tCRIL Github Access issue filing process to get the "Triage" access granted.
