### ISSUE TITLE
[GH Request] Add repository for centralized .tsconfig for TypeScript

### ISSUE THREAD

**Issue by marlonkeating** [openedx/tcril-engineering#643]
### Firm Name

2U

### Urgency

Low Urgency, but would be nice to get approved soon as we're starting to move as an org into wider adoption of TypeScript

### Problem/Request

We would like to create a new repository 'tsconfig' to house a centralized .tsconfig file, which other edx repositories would consume to configure their TypeScript setup.  This would have a similar usage to https://github.com/openedx/browserslist-config.

### Reasoning

Having a centralized .tsconfig file would greatly facilitate adoption of TypeScript across edx's teams and repos, while also serving as a repository for org-wide best practices around the TypeScript language.

**Comment by adamstankiewicz** [comment]
Adding some additional examples of other existing Open edX repositories beyond `browserslist-config` doing something similar as well:
* https://github.com/openedx/eslint-config
* https://github.com/openedx/stylelint-config-edx

**Comment by kdmccormick** [comment]
I'm surprised we want such tiny repositories! Each new repo comes with administrative overhead for tCRIL on-call, the maintainer program, and the CC program.

Is there any reason we wouldn't want to either:
* bundle these into a single frontend-tooling-config repository?
* put all of these in frontend-build?

cc @arbrandes

**Comment by adamstankiewicz** [comment]
> put all of these in frontend-build?

frontend-build is only applicable to MFEs. In theory, a standardized TypeScript config should be applicable outside of MFEs, too.

> bundle these into a single frontend-tooling-config repository?

This approach is related to some ongoing internal discussions at 2U regarding whether a monorepo for our most of our shared, cross-cutting frontend JS libraries would make sense to simplify dev experience and maintenance. I'm hoping we'll bring these early discussions to FWG for more open and broader input/consideration.

That said, we'd still want these packages to shipped to NPM independently as their own independently released NPM packages even if they were all co-located under one repo. Given that, there needs to be tooling in place to support NPM releases from a monorepo (e.g., Lerna).

Historically, (Open) edX has preferred the approach of one repo per technical component (e.g., NPM package), though it seems we're on the cusp of potentially revisiting that existing convention a bit within the frontend ecosystem anyways. To me, this frontend monorepo idea is a larger lift/decision and one that I personally feel shouldn't block creating a new repo for `tsconfig.json` in the short term 😄

**Comment by adamstankiewicz** [comment]
> > That said, we'd still want these packages to shipped to NPM independently as their own independently released NPM packages even if they were all co-located under one repo.
> 
> Why?

For example, it doesn't make sense for consumers who _only_ want to use `eslint-config` to install a package that gets them `eslint-config`, `browserslist-config`, `stylelint-config-edx`, etc. all-in-one which increases the package size.

Additionally, if all these were in a single package, an independent breaking change to `eslint-config`, for instance, would require releasing a new major version for all the config packages rather than just the 1 that changed.

Further, if we were to pursue a frontend monorepo for Open edX, in theory, that monorepo would be including these small config repos as well as larger repos like `@edx/frontend-build`, `@edx/frontend-platform`, `@edx/frontend-component-header`, `@edx/frontend-component-footer`, etc.

It would not make sense to ship all of these under a single NPM package as they each serve significantly different use cases.

**Comment by kdmccormick** [comment]
> increases the package size.

Each package is like a kilobyte, which is negligible, so I assume you're talking about the packages' dependencies (stylelint, eslint, and typescript)? Are there cases where we'd want a JS repo to have one type of static analysis, but not the other two?

> they each serve significantly different use cases.

I think this is where we disagree. Each of `stylelint-config-edx`, `eslint-config`, and now `typescript-config` would be devDependencies in repositories with JS, providing configuration for static analysis tools. I'm not sure what `browserlists-config` does; perhaps that's different.

> Additionally, if all these were in a single package, an independent breaking change to eslint-config, for instance, would require releasing a new major version for all the config packages rather than just the 1 that changed.

I believe this is the same reason why [frontend-platform](https://github.com/openedx/frontend-platform) was originally broken into five separately-versioned NPM packages. It turned out that the overhead of managing version upgrades for each separate package wasn't worth the granularity.

@arbrandes @adamstankiewicz , if you both think this is the right way forward, I'll make the typescript-config repo. I am no expert in frontend tooling. It's just that [openedx has too many repositories](https://github.com/orgs/openedx/repositories), so I'd like to pump the brakes every time we think we need another one.

**Comment by kdmccormick** [comment]
Sorry, one other thing: if we do go forward with this new repository, who will maintain it?

**Comment by arbrandes** [comment]
@kdmccormick, I think that a new repo is the right thing to do now.  None of the alternatives are readily achievable.  If we want to consolidate repos, we need to plan out the effort, _and take it to completion_: historically, the project does not have a good track record finishing migrations.  I think we'd be in a worse place if we had some packages in monorepos and some not, without anybody leading the effort to consolidate and no end in sight.

The maintenance question is a very good one, though.  If it were up to me, I'd say that any new repository should be in the maintainer's pilot by definition, and that a maintainer is a pre-requisite for creating it.

**Comment by adamstankiewicz** [comment]
> > Additionally, if all these were in a single package, an independent breaking change to eslint-config, for instance, would require releasing a new major version for all the config packages rather than just the 1 that changed.
>
> I believe this is the same reason why [frontend-platform](https://github.com/openedx/frontend-platform) was originally broken into five separately-versioned NPM packages. It turned out that the overhead of managing version upgrades for each separate package wasn't worth the granularity.

@kdmccormick To a degree, yes. But those 5 separately-versioned NPM packages largely were intertwined (they relied on each other in many ways), with each having many of their own dependencies, sometimes conflicting with each other. 

Consuming applications needed to pull in and upgrade each of these 5 related NPM packages independently, which was challenging. Co-locating these related packages into a single `frontend-platform` package made sense from that POV.

For these config repos, though, they are truly independent with no crossover or dependencies between them and are intended for different technologies. It is also possible that the tools that we pass these configs to require them to be as distinct NPM packages with their entrypoint as the main `index.js` file in the repo as it typically documented.

[Example](https://github.com/openedx/frontend-build/blob/895422d28e4be70ae297d56051784d8f601aedfe/config/.eslintrc.js#L4):

```js
module.exports = {
  extends: '@edx/eslint-config',
  // ...
};
```

I'm not sure the `extends` config option here would let you do something like `extends: '@edx/frontend-shared-configs/eslint'`, for example.

> [kyle] if we do go forward with this new repository, who will maintain it?
> [adolfo] If it were up to me, I'd say that any new repository should be in the maintainer's pilot by definition, and that a maintainer is a pre-requisite for creating it.

@kdmccormick @arbrandes Agreed, it makes a lot of sense to ensure any new repository has a dedicated maintainer before it gets created. In this situation, while the Enterprise Quokkas squad is proposing the repo, long-term, I'd imagine this repo would fall under the purview of the FED-BOM team who is now the owning squad of most of our cross-cutting JS libraries, including the other config repos like `eslint-config`.

**Comment by kdmccormick** [comment]
>  It is also possible that the tools that we pass these configs to require them to be as distinct NPM packages with their entrypoint as the main index.js file in the repo as it typically documented.

Ah, I didn't realize that JS tools actually expected this pattern. OK, separate NPM packages it is. Thanks for the explanation, @adamstankiewicz .

And I agree with @arbrandes that consolidating multiple NPM packages into one repo is not something we should try to bite off right now. So we do need the new repo.

>  I'd imagine this repo would fall under the purview of the FED-BOM team who is now the owning squad of most of our cross-cutting JS libraries, including the other config repos like eslint-config.

Before I make the new repo, @jmbowman , will FED-BOM commit to maintaining this new `typescript-config` repository?

**Comment by kdmccormick** [comment]
Great. Thanks for bearing with me folks.

I made https://github.com/openedx/typescript-config and gave push-pull-all write access to it. @adamstankiewicz and @jmbowman , you are both admins, feel free to rename & adjust settings as you need to. If you want to add additional admins & writers, though, please file a GitHub request rather than adjusting the access yourselves.

**Comment by adamstankiewicz** [comment]
Thanks @jmbowman for taking on ownership of the repo with FED-BOM and @kdmccormick for creating the new repo! 🙌
