### ISSUE TITLE
[GH Request] Onboard Brian Smith

### ISSUE THREAD

**Issue by arbrandes** [openedx/tcril-engineering#651]
### Firm Name

tCRIL

### User List (case sensitive!) - Please also include in ticket title

* Brian Smith, @brian-smith-tcril 

### Start Date

Feb 2 2023

### Urgency

High urgency: Brian's on call and running into permissions issues

### Special Requests

Brian Smith should be onboarded both as org admin and coding Core Contributor, as per [the nomination thread](https://discuss.openedx.org/t/core-contributor-nomination-brian-smith/9166).  He should have write access to all frontend-related repositories, listed below.

For ease of future administration it is suggested that the following teams be created, and for Brian to be added to `@frontend-all`.

#### `@frontend-mfes-all`

* frontend-platform
* frontend-template-application
* frontend-build
* frontend-app-* (all MFEs)
* frontend-component-* (all MFE components)
* frontend-lib-* (all MFE libraries)
* frontend-enterprise-* (all frontend Enterprise repositories)

#### `@frontend-all`

The above list, plus:

* brand-openedx
* browserslist-config
* studio-frontend
* edx-platform
* paragon
* eslint-config
* stylelint-config-edx
* edx-bootstrap
* edx-ui-toolkit
* cypress-e2e-tests
* frontend-wg

**Comment by kdmccormick** [comment]
What I did do:
* Made Brian an org owner, so he can do on-call next week.
* Almost everything in https://openedx.atlassian.net/wiki/spaces/COMM/pages/2810249408/Administering+a+CC+Committer+Onboarding+Runbook

What I haven't done:
* Making the `frontend` teams suggested above and adding Brian to them.
* Awarded Brian the “Core Contributor” forum badge, since I'm not a forum admin.

@arbrandes Could you handle those last two bits?

**Comment by arbrandes** [comment]
@kdmccormick, will do!

**Comment by arbrandes** [comment]
Done!
