### ISSUE TITLE
[GH Request] Write access to openedx/event-bus-redis

### ISSUE THREAD

**Issue by rgraber** [openedx/tcril-engineering#751]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

We are requesting write access to openedx/event-bus-redis for the members of the 2U Arch BOM team:
Jeremy Bowman - jmbowman
Robert Raposa - robrap
Tim McCormack - timmc-edx
Diana Huang - dianakhuang
Rebecca Graber - rgraber

### Reasoning

We own the event bus on the 2U side and work closely with Axim on it. There will likely be times when we will be making small changes to the redis event bus to keep in sync with various API changes. It will save everyone some time if we have write access.

**Comment by rgraber** [comment]
fyi @robrap  

@bmtcril are there others with write permission at Axim? I can foresee a situation where we do need to something with the redis event bus and you are on vacation and we are all sad. 

We could also for now avoid the issue altogether and just not contribute to the Redis event bus. Given that it is still in version 0 we (2U) can theoretically proceed to just muck about with openedx-events and event-bus-kafka at our leisure and notify Axim when there are changes they will need to incorporate. This won’t always be true but by then hopefully there will be more robust maintainership of event-bus-redis. This relies on you all being willing to take full responsibility for keeping event bus redis up to date.

**Comment by bmtcril** [comment]
@rgraber any Axim on call can always handle emergency reviews and merges. I'd love to have all the help I can get in any way people are able to give it. If it turns out that you, or anyone, are making prs to the repo with any frequency I'd love to sponsor you for a rights expansion to have write access to this repo. I'm sure it would pass quickly because you are known to be awesome.

I'm not sure where communication fell down, since it was before my time at Axim, but what @feanil said is true for all of the new repos that are not contributed by 2U, including for us. I work in forks all the time. We're going to try to get together with folks on the 2U side to see how we can best get that socialized so people don't get unpleasant surprises like this, but please know that it has nothing to do with you, or me, or this repo in specific. We're just trying to manage the project in a way that is fair to the entire community.

**Comment by rgraber** [comment]
Don't worry, I'm not offended :). I'm fine with leaving things how they are until we have reason not to.
