### ISSUE TITLE
Access request for decoupling issues

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#80]
### Requested change

For coordination purposes, please grant access to issues like https://github.com/openedx/decoupling/issues/12 to the following:
    Ned Batchelder nedbat
    David Joy davidjoy
    Jeremy Bowman jmbowman
    Diana Huang dianakhuang
    Rebecca Graber rgraber
    Robert Raposa robrap
    Manjinder Singh jinder1s
    Tim McCormack timmc-edx

Note: It is possible that Ned, Jeremy, and David already have access

### Reasoning

To coordinate on tickets that point to these issues.

**Comment by kdmccormick** [comment]
Thanks @robrap , I just asked the team. Hopefully we'll have this sorted out by tomorrow.

**Comment by kdmccormick** [comment]
@robrap Since we're past the early phases of tCRIL-edX decoupling, we're hoping to now decommission the decoupling repo and project board (because they lead to access issues like this one :)

For the [Transifex ticket you linked](https://github.com/openedx/decoupling/issues/12) as well as any other decoupling issue that's in edX's hands: please have @jmbowman or @nedbat copy the relevant info into your own issue tracker (Jira I assume?) and then close the decoupling issue in favor of the Jira ticket.
